name: build code
on:
 workflow_dispatch:


jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: Actions/checkout@v4
    - name: compile
      run:
       g++ -std=c++11 negarr.cpp proxy.cpp -o main
    - name: upload main to artifact
      uses: action/upload-artifact@v4
      with:
        name: build-output
        path: main
